GET http://localhost:3001/api/users

###

POST http://localhost:3001/api/users Content-Type: application/json

{
"email": "n@n.com", "name": "Noor", "password": "password"
}

###

POST http://localhost:3001/api/users/login Content-Type: application/json

{
"name": "Noor", "password": "password"
}